alt + shift + ctrl - w : open -a "Finder"
alt + shift + ctrl - v : open -a "Preview"
alt + shift + ctrl - p : open -a "Godot"
alt + shift + ctrl - c : open -a "Arc"
alt + shift + ctrl - n : open -a "Obsidian"
alt + shift + ctrl - b : open -a "HTTPie"

alt + shift + ctrl - r : open -a "Music"
alt + shift + ctrl - f : open -a "Spotify"
alt + shift + ctrl - s : open -a "Discord"
alt + shift + ctrl - t : open -a "Alacritty"
alt + shift + ctrl - g : open -a "GitKraken"

alt + shift + ctrl - z : open -a "Messenger"
alt + shift + ctrl - b : open -a "Safari"
alt + shift + ctrl - d : open -a "DataGrip"
