#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
	selected=$1
else
	selected=$(git branch -a | sed 's/remotes\/origin\///g' | tr '* ' '  ' | sort | uniq | fzf)
fi

if [[ -z $selected ]]; then
  echo "No branch selected. Skipping..."
	exit 0
fi

git switch $selected
