#!/usr/bin/env bash

# [g]it [s]witch [b]ranch
# A utility script to speed up git branch switching
#
# Usage
#
# Fuzzy find the branch to switch to
# $ gsb 
#
# Specify the branch to switch to
# $ gsb BRANCH_NAME
#
# Go to the last checked out branch
# $ gsb -

file="$HOME/var/state/gsb.txt"
touch "$file"

repo=$(git rev-parse --show-toplevel)

fuzzy_branch() {
  git branch -a | sed 's/remotes\/origin\///g' | tr '* ' '  ' | sort | uniq | fzf
}

if [[ $# -eq 1 ]]; then
  if [[ "$1" = "-" ]]; then
    prev=$(awk -F '=' -v repo="$repo" '{if ($1 == repo) print $NF}' $file)
    if [[ -z $prev ]]; then
      selected=$(fuzzy_branch)
    else
      selected=$prev
    fi
  else
    selected=$1
  fi
else
  selected=$(fuzzy_branch)
fi

if [[ -z $selected ]]; then
  echo "No branch selected. Skipping..."
  exit 0
fi

curr=$(git branch --show-current)
sed -i '' "/^${repo//\//\\/}=.*/d" "$file"
echo "$repo=$curr" >> "$file"

git switch $selected
