#!/usr/bin/env bash

if [ "$1" == "on" ]; then
    if hash is_dark_mode 2>/dev/null && ! is_dark_mode; then
        echo "Jay is a night owl, disabling light mode..."
        export NEOVIM_BACKGROUND="dark"
        alacritty-colorscheme -V apply "base16-rose-pine.yml"
        dark-mode on
    fi
    echo "Jay has poor eyesight, scaling up to 1080p..."
    SCREEN_ID=$(displayplacer list | sed 1q | sed "s/.*: //g")
    displayplacer "id:$SCREEN_ID res:1920x1080 hz:60 color_depth:8 enabled:true scaling:on origin:(0,0) degree:0"
    echo "Jay mode enabled."
    exit 0
elif [ "$1" == "off" ]; then
    SCREEN_ID=$(displayplacer list | sed 1q | sed "s/.*: //g")
    echo "Jay has left the building, scaling back to 4k..."
    displayplacer "id:$SCREEN_ID res:3008x1692 hz:60 color_depth:8 scaling:on origin:(0,0) degree:0"
    echo "Jay mode disabled."
    exit 0
else
    echo "Usage: taupe [on|off]"
    exit 1
fi
