#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
	selected=$2
else
	selected=$(find ~/Documents/intek ~/Documents/personal -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
	exit 0
fi

selected_name=$(basename "$selected" | tr . _)

if ! tmux has-session -t=$selected_name 2>/dev/null; then
	TMUX='' tmux new-session -ds $selected_name -c $selected
fi

if [[ "${TMUX-}" != '' ]]; then
	tmux switch-client -t $selected_name
else
	tmux attach -t $selected_name
fi
